CREATE TABLE Employee (
    EmployeeId INT IDENTITY(1,1) PRIMARY KEY,
    FirstName VARCHAR(50) NOT NULL,
	LastName VARCHAR(50) NOT NULL,
    EmailID VARCHAR(100) NOT NULL,
    Phone VARCHAR(20) NOT NULL 
);